# Generated by Django 2.1.5 on 2019-09-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guide',
            name='exp',
            field=models.IntegerField(default=0),
        ),
    ]
