# Generated by Django 2.1.5 on 2019-09-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=70)),
                ('lname', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('number', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=18)),
                ('price', models.IntegerField(default=200)),
                ('gender', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=70)),
                ('country', models.CharField(max_length=70)),
                ('pincode', models.IntegerField(default=0)),
            ],
        ),
    ]
