# Generated by Django 2.1.5 on 2019-09-28 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_place_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='place_id',
        ),
    ]
